[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  functions = "netlify/functions"
